#define XOODYAK_CRYPTO_KEYBYTES     16
#define XOODYAK_CRYPTO_NSECBYTES    0
#define XOODYAK_CRYPTO_NPUBBYTES    16
#define XOODYAK_CRYPTO_ABYTES       16
#define XOODYAK_CRYPTO_NOOVERLAP    1
#define XOODYAK_CRYPTO_BYTES        32
#define TINYJAMBU_256_CRYPTO_KEYBYTES 32
#define TINYJAMBU_256_CRYPTO_NSECBYTES 0
#define TINYJAMBU_256_CRYPTO_NPUBBYTES 12
#define TINYJAMBU_256_CRYPTO_ABYTES 8
#define TINYJAMBU_256_CRYPTO_NOOVERLAP 1
#define TINYJAMBU_192_CRYPTO_KEYBYTES  24
#define TINYJAMBU_192_CRYPTO_NSECBYTES 0
#define TINYJAMBU_192_CRYPTO_NPUBBYTES 12
#define TINYJAMBU_192_CRYPTO_ABYTES 8
#define TINYJAMBU_192_CRYPTO_NOOVERLAP 1
#define TINYJAMBU_128_CRYPTO_KEYBYTES 16
#define TINYJAMBU_128_CRYPTO_NSECBYTES 0
#define TINYJAMBU_128_CRYPTO_NPUBBYTES 12
#define TINYJAMBU_128_CRYPTO_ABYTES 8
#define TINYJAMBU_128_CRYPTO_NOOVERLAP 1
#define PHOTONBEETLE_128_CRYPTO_KEYBYTES 16
#define PHOTONBEETLE_128_CRYPTO_NSECBYTES 0
#define PHOTONBEETLE_128_CRYPTO_NPUBBYTES 16
#define PHOTONBEETLE_128_CRYPTO_ABYTES 16
#define PHOTONBEETLE_128_CRYPTO_NOOVERLAP 1

#define CRYPTO_AEAD_TYPE XOODYAK_AEAD
#define CRYPTO_KEYBYTES 16
#define CRYPTO_NSECBYTES 0
#define CRYPTO_NPUBBYTES 12
#define CRYPTO_ABYTES 8
#define CRYPTO_NOOVERLAP 1

#ifdef MAKE_XOODYAK
#define CRYPTO_AEAD_TYPE    XOODYAK_AEAD
#define CRYPTO_KEYBYTES     XOODYAK_CRYPTO_KEYBYTES
#define CRYPTO_NSECBYTES    XOODYAK_CRYPTO_NSECBYTES
#define CRYPTO_NPUBBYTES    XOODYAK_CRYPTO_NPUBBYTES
#define CRYPTO_ABYTES       XOODYAK_CRYPTO_ABYTES
#define CRYPTO_NOOVERLAP    XOODYAK_CRYPTO_NOOVERLAP
#endif

// #ifdef MAKE_TINYJAMBU_128
// #define CRYPTO_AEAD_TYPE    TINYJAMBU_128_AEAD
// #define CRYPTO_KEYBYTES     TINYJAMBU_128_CRYPTO_KEYBYTES
// #define CRYPTO_NSECBYTES    TINYJAMBU_128_CRYPTO_NSECBYTES
// #define CRYPTO_NPUBBYTES    TINYJAMBU_128_CRYPTO_NPUBBYTES
// #define CRYPTO_ABYTES       TINYJAMBU_128_CRYPTO_ABYTES
// #define CRYPTO_NOOVERLAP    TINYJAMBU_128_CRYPTO_NOOVERLAP
// #endif

// #ifdef MAKE_TINYJAMBU_192
// #define CRYPTO_AEAD_TYPE    TINYJAMBU_192_AEAD
// #define CRYPTO_KEYBYTES     TINYJAMBU_192_CRYPTO_KEYBYTES
// #define CRYPTO_NSECBYTES    TINYJAMBU_192_CRYPTO_NSECBYTES
// #define CRYPTO_NPUBBYTES    TINYJAMBU_192_CRYPTO_NPUBBYTES
// #define CRYPTO_ABYTES       TINYJAMBU_192_CRYPTO_ABYTES
// #define CRYPTO_NOOVERLAP    TINYJAMBU_192_CRYPTO_NOOVERLAP
// #endif

// #ifdef MAKE_TINYJAMBU_256
// #define CRYPTO_AEAD_TYPE    TINYJAMBU_256_AEAD
// #define CRYPTO_KEYBYTES     TINYJAMBU_256_CRYPTO_KEYBYTES
// #define CRYPTO_NSECBYTES    TINYJAMBU_256_CRYPTO_NSECBYTES
// #define CRYPTO_NPUBBYTES    TINYJAMBU_256_CRYPTO_NPUBBYTES
// #define CRYPTO_ABYTES       TINYJAMBU_256_CRYPTO_ABYTES
// #define CRYPTO_NOOVERLAP    TINYJAMBU_256_CRYPTO_NOOVERLAP
// #endif

#ifdef MAKE_PHOTONBEETLE_128
#define CRYPTO_AEAD_TYPE    PHOTONBEETLE_128_AEAD
#define CRYPTO_KEYBYTES     PHOTONBEETLE_128_CRYPTO_KEYBYTES
#define CRYPTO_NSECBYTES    PHOTONBEETLE_128_CRYPTO_NSECBYTES
#define CRYPTO_NPUBBYTES    PHOTONBEETLE_128_CRYPTO_NPUBBYTES
#define CRYPTO_ABYTES       PHOTONBEETLE_128_CRYPTO_ABYTES
#define CRYPTO_NOOVERLAP    PHOTONBEETLE_128_CRYPTO_NOOVERLAP
#endif
